Feat: add ICQ configuration NTRN-248
neutron-org/testnets pull request #108
Opened 2022-11-03 06:42 UTC by foxpy

This PR adds template ICQ configuration and docs on how to fill it.

2022-11-04 14:14 UTC, albertandrejev requested changes

2022-11-04 14:14 UTC, albertandrejev commented on neutron-devnet-1/icq-relayer/.env
> +RELAYER_NEUTRON_CHAIN_HOME_DIR=/path/to/home
Please leave these option empty (I guess in this case relayer will halt?)

2022-11-04 14:14 UTC, albertandrejev commented on neutron-devnet-1/icq-relayer/.env
> +RELAYER_STORAGE_PATH=/path/to/storage
Please leave these option empty (I guess in this case relayer will halt?)

2022-11-04 14:14 UTC, albertandrejev commented on neutron-devnet-1/icq-relayer/README.md
> +## Install relayer
Please put required minimum Go version here.

2022-11-07 13:11 UTC, foxpy commented on neutron-devnet-1/icq-relayer/.env
> +RELAYER_NEUTRON_CHAIN_HOME_DIR=/path/to/home
Tested, it doesn't halt. It fallbacks to "keyring-test" somewhere inside.

2022-11-07 13:16 UTC, foxpy commented on neutron-devnet-1/icq-relayer/.env
> +RELAYER_STORAGE_PATH=/path/to/storage
Yes, it will. I will change this line.

2022-11-07 13:22 UTC, foxpy commented on neutron-devnet-1/icq-relayer/README.md
> +## Install relayer
Fixed

2022-11-07 13:28 UTC, albertandrejev submitted a review, later dismissed

2022-11-07 15:34 UTC, NeverHappened commented on quark/icq-relayer/README.md
> +- RELAYER_TARGET_CHAIN_CONNECTION_ID
These variables won't be needed to fill in if we merge this https://github.com/neutron-org/neutron-query-relayer/pull/51
`RELAYER_NEUTRON_CHAIN_CLIENT_ID` , `RELAYER_TARGET_CHAIN_CONNECTION_ID`, `RELAYER_TARGET_CHAIN_CLIENT_ID`

2022-11-07 15:35 UTC, NeverHappened commented on quark/icq-relayer/.env
> +RELAYER_TARGET_CHAIN_CHAIN_ID=
see https://github.com/neutron-org/testnets/pull/108/files#r1015570016

2022-11-07 15:36 UTC, NeverHappened commented on quark/icq-relayer/.env
> +RELAYER_NEUTRON_CHAIN_CHAIN_ID=quark-1
also do not need if [this](https://github.com/neutron-org/neutron-query-relayer/pull/51/files) gets merged

2022-11-07 15:37 UTC, NeverHappened commented on quark/icq-relayer/.env
> +RELAYER_NEUTRON_CHAIN_CLIENT_ID=07-tendermint-0
also do not need if [this](https://github.com/neutron-org/neutron-query-relayer/pull/51/files) gets merged

2022-11-07 15:42 UTC, NeverHappened requested changes
as we decided to merge https://github.com/neutron-org/neutron-query-relayer/pull/51/files
we need to change this according to new simplified config

2022-11-07 15:42 UTC, NeverHappened commented on quark/icq-relayer/.env
> +RELAYER_NEUTRON_CHAIN_TIMEOUT=1000s
don't need to specify (has default value) if this gets merged https://github.com/neutron-org/neutron-query-relayer/pull/51/files

2022-11-07 15:42 UTC, NeverHappened commented on quark/icq-relayer/.env
> +RELAYER_TARGET_CHAIN_TIMEOUT=1000s
don't need to specify (has default value) if this gets merged https://github.com/neutron-org/neutron-query-relayer/pull/51/files

2022-11-07 16:24 UTC, foxpy commented on quark/icq-relayer/README.md
> +- RELAYER_TARGET_CHAIN_CONNECTION_ID
Please ping me when it is merged, and I will be happy to remove them!

2022-11-07 16:25 UTC, foxpy commented on quark/icq-relayer/README.md
> +- RELAYER_TARGET_CHAIN_CONNECTION_ID
Oh, wait, so are we 100% certain to merge it? Then I have to remove these options right now.

2022-11-07 16:40 UTC, NeverHappened commented on quark/icq-relayer/README.md
> +- RELAYER_TARGET_CHAIN_CONNECTION_ID
@oopcode are we gonna merge it?

2022-11-07 20:35 UTC, albertandrejev submitted a review, later dismissed

2022-11-08 08:23 UTC, pr0n00gler approved these changes

2022-11-08 08:28 UTC, NeverHappened commented on quark/icq-relayer/.env
> -RELAYER_TARGET_CHAIN_VALIDATOR_ACCOUNT_PREFIX=junovaloper # or cosmosvaloper
these two options were necessary?

2022-11-08 10:12 UTC, NeverHappened commented on quark/icq-relayer/.env
> -RELAYER_TARGET_CHAIN_VALIDATOR_ACCOUNT_PREFIX=junovaloper # or cosmosvaloper
fixed it

2022-11-08 10:13 UTC, NeverHappened approved these changes

2022-11-08 12:23 UTC, merged