Igor_K Gentx & Peer
neutron-org/testnets pull request #111
Opened 2022-11-03 08:12 UTC by nopoxoBHuk

2022-11-04 14:16 UTC, albertandrejev requested changes

2022-11-04 14:16 UTC, albertandrejev commented on quark/gentxs/Igor-K-gentx
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Igor_K","identity":"9DABADFFA9F52968","website":"","security_contact":"","details":""},"commission
Please update `max_change_rate` in accordance with the documentation.

2022-11-06 14:49 UTC, nopoxoBHuk commented
Thanks!  I am update gentx file

2022-11-06 18:23 UTC, albertandrejev approved these changes

2022-11-07 07:12 UTC, nopoxoBHuk commented
moniker: Igor_K

discord: Igor_K#1129
valoper: neutronvaloper1cxr2g6ska0xsdl9hmsa9rsnzt7gkj65zxlu47r

2022-11-07 22:17 UTC, merged