Add GenTX moon
neutron-org/testnets pull request #112
Opened 2022-11-03 08:18 UTC by Damian00000

2022-11-04 14:17 UTC, albertandrejev requested changes

2022-11-04 14:17 UTC, albertandrejev commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"moon","identity":"31A1172488DADFDA","website":"","security_contact":"","details":"professional val
Please update `max_change_rate` in accordance with the documentation.

2022-11-06 05:56 UTC, Damian00000 commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"moon","identity":"31A1172488DADFDA","website":"","security_contact":"","details":"professional val
Updated

2022-11-06 06:08 UTC, Damian00000 commented
Moniker: moon
Twitter page: https://twitter.com/Denis24534
Team Discord: Denis#6284
Neutron Valoper: neutronvaloper1ha47m8l33c2esa8hzgwwgc24xaj64sqkr2507w

2022-11-06 18:23 UTC, albertandrejev approved these changes

2022-11-07 12:15 UTC, merged

2022-11-10 10:37 UTC, Medniyy commented
Unfortunately, we can't give you the validator role because you've not entered our Discord! 
This is the link: https://discord.gg/r82yeMu9Rf
Please enter and ping soi2studio#1446 with the link of this PR to receive your role.