PigCash gentx + peers
neutron-org/testnets pull request #152
Opened 2022-11-04 17:50 UTC by cash21r

- PigCash 
- staking.imweb.me
- PigCash#8647
- neutronvaloper1gjhqsza7x95l906f7q5qqghssp2cq7z5y42vep

2022-11-04 18:57 UTC, albertandrejev requested changes

2022-11-04 18:57 UTC, albertandrejev commented on quark/gentxs/PigCash-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"PigCash","identity":"","website":"staking.imweb.me","security_contact":"","details":"7098B6BD7C8A3
Please recreate your gentx, it seems that something wrong with it. Please control `chain-id` (it should be `quark-1`) that was used to create this gentx. Also if you tried to update gentx details manually please don't do it because manual update of the gentx corrupts it.

2022-11-05 02:40 UTC, cash21r commented on quark/gentxs/PigCash-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"PigCash","identity":"","website":"staking.imweb.me","security_contact":"","details":"7098B6BD7C8A3
It's corrected..!! Thanks~!

2022-11-05 17:44 UTC, albertandrejev approved these changes

2022-11-06 22:22 UTC, merged