GNST.getnx
neutron-org/testnets pull request #170
Opened 2022-11-05 12:24 UTC by Genstamindband

2022-11-05 17:31 UTC, albertandrejev requested changes

2022-11-05 17:31 UTC, albertandrejev commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"GNST","identity":"","website":"https://github.com/Genstamindband","security_contact":"","details":
Please update gentx file name to something unique. You can rename it to something like: `gentx-gnst.json` for example.

2022-11-06 11:13 UTC, Genstamindband commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"GNST","identity":"","website":"https://github.com/Genstamindband","security_contact":"","details":
Done!

2022-11-06 20:43 UTC, albertandrejev requested changes

2022-11-06 20:43 UTC, albertandrejev commented on quark/gentxs/README.md
> +Moniker: GNST
You do not need to put anything into this file, PR comment is enough. Please remove changes from this file

2022-11-07 08:05 UTC, Genstamindband commented on quark/gentxs/README.md
> +Moniker: GNST
Done

2022-11-07 08:08 UTC, Genstamindband commented
Webpage: https://twitter.com/genstamindband

 Discord handle: Genstamindband#6713, FlakySizzler#9185, hedji#5037, DimaRCR7#0690, Dr_Atavov_PRO#0484

 neutronvaloper1wggg4ge3lgc5zpa3njk9eyxjkduatsedn8g49p

2022-11-07 17:40 UTC, closed without merging