Create  anode gentx
neutron-org/testnets pull request #192
Opened 2022-11-05 20:55 UTC by asverty

anode
https://twitter.com/alekh_w
dmvrt#7238
TIM#1202
neutronvaloper1pjgdwtmvw5har8qezmkaj9zjjzewvt9hp7yedl

2022-11-06 17:55 UTC, albertandrejev approved these changes

2022-11-07 11:50 UTC, albertandrejev requested changes

2022-11-07 11:50 UTC, albertandrejev commented on quark/gentxs/anode_gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"anode","identity":"B408D693B9E27CB2","website":"https://twitter.com/alekh_w","security_contact":"v
Please recreate your gentx, it seems that something wrong with it. Please control `chain-id` (should be `quark-1`) that was used to create this gentx. Also if you tried to update gentx details manually please don't do it because manual update of the gentx corrupts it.

2022-11-07 12:45 UTC, asverty commented on quark/gentxs/anode_gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"anode","identity":"B408D693B9E27CB2","website":"https://twitter.com/alekh_w","security_contact":"v
Thank you! Updated file `anode_gentx.json`

2022-11-07 14:38 UTC, asverty commented on quark/gentxs/anode_gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"anode","identity":"B408D693B9E27CB2","website":"https://twitter.com/alekh_w","security_contact":"v
Regenerate gentx.json and include peer.txt files.

2022-11-07 20:39 UTC, albertandrejev requested changes

2022-11-07 20:39 UTC, albertandrejev commented on quark/gentxs/anode_new_gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"anode","identity":"","website":"https://twitter.com/alekh_w","security_contact":"","details":" ⚛
Still something wrong with your genesis. Please remove `~/.neutrond` directory and init new one using `neutrond init node --chain-id quark-1` command and try to create gentx again.

2022-11-08 09:41 UTC, asverty commented on quark/gentxs/anode_new_gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"anode","identity":"","website":"https://twitter.com/alekh_w","security_contact":"","details":" ⚛
Deleted `~/neutrond` directory and re-init. Created new `gentx_anode.json` without emojies in `--details`, updated peer.

2022-11-10 10:55 UTC, closed without merging