Validator.run gentx + peers
neutron-org/testnets pull request #197
Opened 2022-11-06 02:21 UTC by ardapda

Moniker: Validator.run
Website: https://validator.run/
Team Discord: arda | Validator.run#8670
Neutron Valoper: neutronvaloper15tq88p9xluyfmzq79nw3rjj85hq46lwnnpacvp

2022-11-06 18:01 UTC, albertandrejev requested changes

2022-11-06 18:01 UTC, albertandrejev commented on quark/gentxs/gentx-Validatorrun.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Validator.run","identity":"2CC4D67B2136C051","website":"https://www.validator.run","security_conta
Please update `max_change_rate`, and `max_rate` in accordance with the documentation.

2022-11-07 08:03 UTC, ardapda commented on quark/gentxs/gentx-Validatorrun.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Validator.run","identity":"2CC4D67B2136C051","website":"https://www.validator.run","security_conta
Updated the values  in accordance with the documentation, please check.

2022-11-07 11:51 UTC, albertandrejev requested changes

2022-11-07 11:51 UTC, albertandrejev commented on quark/gentxs/gentx-Validatorrun.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Validator.run","identity":"2CC4D67B2136C051","website":"https://www.validator.run","security_conta
Please recreate your gentx, it seems that something wrong with it. Please control `chain-id` (should be `quark-1`) that was used to create this gentx. Also if you tried to update gentx details manually please don't do it because manual update of the gentx corrupts it.

2022-11-08 10:34 UTC, ardapda commented on quark/gentxs/gentx-Validatorrun.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Validator.run","identity":"2CC4D67B2136C051","website":"https://www.validator.run","security_conta
Thanks for taking time.
We've deleted the old files (gentx + peer) and recreated them once more, followed by submitting the PR.
Please check, thank you.
New gentx: [1bdc669](https://github.com/neutron-org/testnets/pull/197/commits/1bdc6695fd2386d545e13244f260dda4614dac20)
New peer: [6b3899a](https://github.com/neutron-org/testnets/pull/197/commits/6b3899ab1c261a69b8a2b6abd9eaf7f608459f08)

2022-11-10 10:55 UTC, closed without merging