Create gentx-nadejda
neutron-org/testnets pull request #203
Opened 2022-11-06 09:57 UTC by nadyacoin

nadejda
https://twitter.com/NTarabukina
tarabukinanadejda#9639
neutronvaloper14fjaf9dv0d7ehvcjyv38w6pcs0uevrx6yn6u4k

2022-11-06 18:05 UTC, albertandrejev requested changes

2022-11-06 18:05 UTC, albertandrejev commented on quark/peers/README.md
> +474237bf04698956c3acee3286ddf199a70ac616@95.217.57.232:56656
Please use another file name for peer

2022-11-07 20:40 UTC, albertandrejev approved these changes

2022-11-07 20:40 UTC, merged

2022-11-10 10:37 UTC, Medniyy commented
Unfortunately, we can't give you the validator role because you've not entered our Discord! 
This is the link: https://discord.gg/r82yeMu9Rf
Please enter and ping soi2studio#1446 with the link of this PR to receive your role.