D-stake gentx and peer
neutron-org/testnets pull request #21
Opened 2022-11-01 07:41 UTC by donadel01

2022-11-03 20:00 UTC, albertandrejev requested changes

2022-11-03 20:00 UTC, albertandrejev commented on quark/gentxs/gentx-ee4ab1f713ab01e6b2e4a852ecd2cef459fa4fc7.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"D-stake","identity":"21A67C27F1A9CD69","website":"https://www.d-stake.xyz","security_contact":"","
Please update `max_change_rate` and `max_rate` in accordance with documentation.

2022-11-03 20:53 UTC, donadel01 commented on quark/gentxs/gentx-ee4ab1f713ab01e6b2e4a852ecd2cef459fa4fc7.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"D-stake","identity":"21A67C27F1A9CD69","website":"https://www.d-stake.xyz","security_contact":"","
@albertandrejev  updated

2022-11-04 19:05 UTC, albertandrejev approved these changes

2022-11-07 19:13 UTC, Medniyy commented
Hey there! Some additional details should be provided in the description!
Check this:

https://github.com/neutron-org/testnets/tree/main/quark#fill-pull-request-description

2022-11-07 20:34 UTC, donadel01 commented
D-stake
https://www.d-stake.xyz
donadel#7181
neutronvaloper1npv2wy7vvfkgr2vr05afe3jq0qtyqwlne02tvx

2022-11-07 21:53 UTC, merged