roadz-gentx
neutron-org/testnets pull request #226
Opened 2022-11-06 20:04 UTC by ryssroad

2022-11-06 21:24 UTC, albertandrejev requested changes

2022-11-06 21:24 UTC, albertandrejev commented on quark/gentxs/roadz-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"59C6436442DEB1B2","website":"https://systemd.run","security_contact":"","detail
Please recreate your gentx, it seems that something wrong with it. Please control `chain-id` (it should be `quark-1`) that was used to create this gentx. Also if you tried to update gentx details manually please don't do it because manual update of the gentx corrupts it.

2022-11-06 21:30 UTC, ryssroad commented on quark/gentxs/roadz-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"59C6436442DEB1B2","website":"https://systemd.run","security_contact":"","detail
recreated, thx

2022-11-06 22:06 UTC, ryssroad commented on quark/gentxs/roadz-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"59C6436442DEB1B2","website":"https://systemd.run","security_contact":"","detail
However, I don't see any mention of "chain-id" in gentx.json although it is present in the command
```
neutrond gentx wallet 1000000000untrn --output-document=gentx.json \
  --chain-id=quark-1 \
  --moniker="roadz" \
  --website=https://systemd.run \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1" \
  --keyring-backend os
```

2022-11-06 22:09 UTC, ryssroad commented on quark/gentxs/roadz-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"59C6436442DEB1B2","website":"https://systemd.run","security_contact":"","detail
```
root@vmi1015431:~/neutron# neutrond version --long
name: neutron
server_name: neutrond
version: 0.0.1
commit: 750ec1bfdc7831d2782e5d2109362a0874904cf6
build_tags: netgo,ledger
go: go version go1.19 linux/amd64
```

2022-11-07 11:54 UTC, albertandrejev requested changes

2022-11-07 11:54 UTC, albertandrejev commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"","website":"https://systemd.run","security_contact":"","details":""},"commissi
Please rename this file.

2022-11-07 12:35 UTC, ryssroad commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"roadz","identity":"","website":"https://systemd.run","security_contact":"","details":""},"commissi
renamed

2022-11-07 20:42 UTC, albertandrejev requested changes
Please do not touch gentxs/gentx.json file at all. It should not be empty. It contains gentx of other validator.

2022-11-10 10:55 UTC, closed without merging