gentx+peers-Roxy
neutron-org/testnets pull request #287
Opened 2022-11-07 17:41 UTC by roxy555

2022-11-07 20:09 UTC, albertandrejev requested changes

2022-11-07 20:09 UTC, albertandrejev commented on quark/gentxs/gentx-Roxy.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Roxy","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.05000
Please recreate your gentx, it seems that something wrong with it. Please control `chain-id` (should be `quark-1`) that was used to create this gentx. Also if you tried to update gentx details manually please don't do it because manual update of the gentx corrupts it.

2022-11-08 03:21 UTC, roxy555 commented on quark/gentxs/gentx-Roxy.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Roxy","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.05000
I corrected it

2022-11-10 10:41 UTC, closed without merging

2022-11-12 17:52 UTC, roxy555 commented
Roksana#2951
777anna777#6147