add keys generation
neutron-org/testnets pull request #348
Opened 2022-11-09 21:56 UTC by oldremez

2022-11-09 23:21 UTC, albertandrejev requested changes

2022-11-09 23:21 UTC, albertandrejev commented on quark/icq-relayer/README.md
> +Run `neutrond keys add my_wallet --recover --home $HOME --keyring-backend test` and input your mnemonic.
`--home` should point to neutron home directory which is `$HOME/.neutrond` whereas you are using `$HOME`, are you sure that it is expected value?

2022-11-09 23:21 UTC, albertandrejev commented on quark/testcases/ICA+ICQ.md
> +2. Go to the [Faucet](http://23.109.159.28/) and get tokens for the addresses you generated on previous step;
We have this address for faucet http://faucet.quark.ntrn.info/

2022-11-09 23:21 UTC, albertandrejev commented on quark/testcases/ICA+ICQ.md
> +3. Make sure tx is passed at the Neutron testnet explorer: http://23.109.159.28:3333/accounts/<your_relayer_address>.
Explorer will be on this address http://explorer.quark.ntrn.info/

2022-11-09 23:21 UTC, albertandrejev commented on quark/testcases/ICA+ICQ.md
>  4. Collect the output and paste in to the results [submission form](https://docs.google.com/forms/d/e/1FAIpQLScZGxOQ44_sY96e7IODGwG_qTRrVnrnJyI7vyRT8QN3cUSOwQ/viewform),
we have short URL for form https://forms.gle/cyEdWfFTygkvcLEQ7

2022-11-10 22:47 UTC, oldremez commented on quark/testcases/ICA+ICQ.md
> +2. Go to the [Faucet](http://23.109.159.28/) and get tokens for the addresses you generated on previous step;
Agree; thought we were to update links with a separate PR though but fixed

2022-11-10 22:47 UTC, oldremez commented on quark/testcases/ICA+ICQ.md
> +3. Make sure tx is passed at the Neutron testnet explorer: http://23.109.159.28:3333/accounts/<your_relayer_address>.
Same as previous

2022-11-10 22:48 UTC, oldremez commented on quark/testcases/ICA+ICQ.md
>  4. Collect the output and paste in to the results [submission form](https://docs.google.com/forms/d/e/1FAIpQLScZGxOQ44_sY96e7IODGwG_qTRrVnrnJyI7vyRT8QN3cUSOwQ/viewform),
It's not even in the changes being made in this PR 🙃 But replaced the link to shorten one anyway

2022-11-10 23:50 UTC, oldremez commented on quark/icq-relayer/README.md
> +Run `neutrond keys add my_wallet --recover --home $HOME --keyring-backend test` and input your mnemonic.
Yeah, my bad… Actually, I decided just to revert my changes and leave the instruction as is. At first, I didn't like the /path/to/home placeholder and wanted to change it to something more proper but haven't found a better way to do that so far so now I propose to let it be as is.

2022-11-11 09:18 UTC, albertandrejev submitted a review, later dismissed

2022-11-11 10:33 UTC, foxpy requested changes

2022-11-11 10:33 UTC, foxpy commented on quark/testcases/ICA+ICQ.md
> +2. Go to the [Faucet](http://faucet.quark.ntrn.info/) and get tokens for the addresses you generated on previous step;
Is it an instruction for validators? I thought they are expected to use their own funds instead of spending their life on faucets?

2022-11-11 10:33 UTC, foxpy commented on quark/testcases/ICA+ICQ.md
> +- For simplicity, you can re-use the mnemonic of `ibc-relayer` key (Keplr -> Add Account -> Import existing account);
Yes, but doing that could trigger issues with account sequence id.

2022-11-11 10:42 UTC, oldremez commented on quark/testcases/ICA+ICQ.md
> +2. Go to the [Faucet](http://faucet.quark.ntrn.info/) and get tokens for the addresses you generated on previous step;
I mean, the relayers in this manual are deployed for testing scenario purposes and aren't really supposed to work long-term. And during testing scenario we ask validators to get funds with faucets multiple times, and faucet's funds should be enough. Even if those relayers are going to be used in a long-term they can be topped up with own funds later anyway but that's out-of-scope of this instruction I believe.

2022-11-11 11:41 UTC, oldremez commented on quark/testcases/ICA+ICQ.md
> +- For simplicity, you can re-use the mnemonic of `ibc-relayer` key (Keplr -> Add Account -> Import existing account);
No it's not since it'll  be account on different chains from the same seed (`ibc-relayer` key is a Neutron key and here we're talking Hub/Juno key).
Actually it's not going to case any issues but allows to use the same mnemonic for `NEUTRON_MNEMONIC` and `TARGET_CHAIN_MNEMONIC` in hermes config)

2022-11-11 12:09 UTC, foxpy approved these changes

2022-11-11 12:11 UTC, merged