NakoTurk gentx & peer
neutron-org/testnets pull request #40
Opened 2022-11-01 11:01 UTC by okannako

2022-11-03 20:13 UTC, albertandrejev requested changes

2022-11-03 20:13 UTC, albertandrejev commented on quark/gentxs/gentx-NakoTurk.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"NakoTurk","identity":"CD2574B68358E7B3","website":"https://twitter.com/NakoTurk","security_contact
Please recreate your genesis. Please check chain id that was used to create it. Also if you tried to update it manually eg. to add some missed data, please do not do that, it corrupts gentx.

2022-11-03 21:42 UTC, okannako commented on quark/gentxs/gentx-NakoTurk.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"NakoTurk","identity":"CD2574B68358E7B3","website":"https://twitter.com/NakoTurk","security_contact
okey, fixed and update. Can you check again ?

2022-11-04 19:06 UTC, albertandrejev approved these changes

2022-11-06 22:18 UTC, merged

2022-11-10 09:34 UTC, Medniyy commented
Hey there! Some additional details should be provided in the description! 
Check this:
https://github.com/neutron-org/testnets/tree/main/quark#fill-pull-request-description