Kalia Network gentx & peer
neutron-org/testnets pull request #43
Opened 2022-11-01 11:21 UTC by KaliaNetwork

2022-11-03 20:16 UTC, albertandrejev requested changes

2022-11-03 20:16 UTC, albertandrejev commented on quark/gentxs/gentx-KaliaNetwork.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Kalia Network","identity":"3D6E2861B47F2F9F","website":"https://kalia.network","security_contact":
Please update `max_change_rate` and `max_rate` in accordance with the documentation.

2022-11-03 23:12 UTC, KaliaNetwork commented on quark/gentxs/gentx-KaliaNetwork.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Kalia Network","identity":"3D6E2861B47F2F9F","website":"https://kalia.network","security_contact":
Dear albert, we have opened a ticket in Discord. Could you check, please?

2022-11-03 23:50 UTC, KaliaNetwork commented on quark/gentxs/gentx-KaliaNetwork.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Kalia Network","identity":"3D6E2861B47F2F9F","website":"https://kalia.network","security_contact":
gentx is updated

2022-11-04 01:29 UTC, KaliaNetwork commented
- Kalia Network
- https://kalia.network/
- Kalia Network#1013   and   sr#3753
- neutronvaloper1zd6z7r658lyck4qgp0vasjhl7e2whnt3jy44ee

2022-11-04 09:43 UTC, albertandrejev approved these changes

2022-11-06 21:27 UTC, merged