add 0base.vc gentx & peer
neutron-org/testnets pull request #49
Opened 2022-11-01 14:44 UTC by jjangg96

2022-11-03 20:38 UTC, albertandrejev requested changes

2022-11-03 20:38 UTC, albertandrejev commented on quark/gentxs/0base.vc-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"0base.vc","identity":"67A577430DBBCEE0","website":"https://0base.vc","security_contact":"0@0base.v
Please update `max_change_rate` and `max_rate` in accordance with the documentation.

2022-11-03 20:57 UTC, jjangg96 commented on quark/gentxs/0base.vc-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"0base.vc","identity":"67A577430DBBCEE0","website":"https://0base.vc","security_contact":"0@0base.v
Changed. 
Thank you.

2022-11-04 19:07 UTC, albertandrejev approved these changes

2022-11-06 18:36 UTC, merged