feat: validators testing script
neutron-org/testnets pull request #5
Opened 2022-10-31 21:27 UTC by ratik

2022-11-01 06:46 UTC, foxpy requested changes

2022-11-01 06:46 UTC, foxpy commented on quark/testcases/ica/README.md
> +You don't have `atom` you can go through the following steps:
```suggestion
If you don't have `atom`, then you can go through the following steps:
```

2022-11-01 06:46 UTC, foxpy commented on quark/testcases/ica/README.md
> +- run this script on your server `./validator_test.sh /place/where/contracts/were/uploaded/to/neutron_validators_test.wasm YOUR_CONNECTION_ID`
People usually are not that verbose when specifying path prefixes:
```suggestion
- run this script on your server `./validator_test.sh /path/to/contracts/neutron_validators_test.wasm YOUR_CONNECTION_ID`
```

2022-11-01 08:25 UTC, foxpy reviewed
Looks good, yet I am going to test it further today.

2022-11-02 10:36 UTC, oopcode commented on quark/testcases/ica/README.md
> +[Install Hermes for quark-1](https://www.notion.so/Install-Hermes-for-quark-1-8137dc949630488fb49a562660c745bb)
please reference the instruction in our github https://github.com/neutron-org/testnets/blob/main/quark/ibc-relayer/instruction.md

2022-11-02 13:24 UTC, foxpy approved these changes

2022-11-07 12:28 UTC, foxpy commented on quark/testcases/ica/README.md
> +[Install Hermes for quark-1](https://www.notion.so/Install-Hermes-for-quark-1-8137dc949630488fb49a562660c745bb)
In fact, this instruction is not even public.

2022-11-07 12:29 UTC, foxpy requested changes
I will approve it back when links to private documentation are fixed.

2022-11-07 12:37 UTC, foxpy requested changes

2022-11-07 12:37 UTC, foxpy commented on quark/testcases/ica/README.md
> +- Upload [testing script](https://github.com/neutron-org/neutron-contracts/blob/fae4fbfb6496fb9eeea6e7a3b39dfb0816a4a6fe/validator_test.sh) to your node
I don't like having a link to a particular commit hash here. Maybe just specify audit fixes branch and path to script?

2022-11-07 12:37 UTC, foxpy commented on quark/testcases/ica/README.md
> +- Upload [testing script](https://github.com/neutron-org/neutron-contracts/blob/fae4fbfb6496fb9eeea6e7a3b39dfb0816a4a6fe/validator_test.sh) to your node
And why did you upload your script here by the way if you ask users to download it from another repo?

2022-11-07 12:39 UTC, ratik commented on quark/testcases/ica/README.md
> +- Upload [testing script](https://github.com/neutron-org/neutron-contracts/blob/fae4fbfb6496fb9eeea6e7a3b39dfb0816a4a6fe/validator_test.sh) to your node
fixed

2022-11-07 12:41 UTC, foxpy requested changes

2022-11-07 12:41 UTC, foxpy commented on quark/testcases/ica/README.md
> +- At first get artifacts from [https://github.com/neutron-org/neutron-contracts/tree/main/artifacts](https://github.com/neutron-org/neutron-contracts/tree/main/artifacts) (TODO: update when we get it
The branch sure is wrong, and I guess this TODO can be removed now.

2022-11-07 13:01 UTC, foxpy approved these changes

2022-11-07 15:17 UTC, merged