KruGGoK Gentx && Peer
neutron-org/testnets pull request #58
Opened 2022-11-01 22:57 UTC by KruGGoK

2022-11-03 20:55 UTC, albertandrejev requested changes

2022-11-03 20:55 UTC, albertandrejev commented on quark/gentxs/KruGGoK.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"KruGGoK","identity":"CF7EB9C1D61DE09A","website":"https://stakesnodes.com","security_contact":"","
Please update `max_change_rate` in accordance with the documentation.

2022-11-05 21:20 UTC, KruGGoK reviewed
update --commission-max-change-rate="0.01"

2022-11-05 21:25 UTC, KruGGoK commented
moniker: KruGGoK
website: https://stakesnodes.com
discord: KruGGoK#3986
valoper: neutronvaloper1lu2v0uf4ap7hyvyu7yk9j9zdfwgyt538ax83ln

2022-11-06 18:21 UTC, albertandrejev approved these changes

2022-11-06 22:28 UTC, merged