RoundTable21 gentx and peer files
neutron-org/testnets pull request #67
Opened 2022-11-02 08:25 UTC by wildcommunist

+ Added gentx.json file
+ Added roundtable21.peer file

2022-11-03 21:11 UTC, albertandrejev requested changes

2022-11-03 21:11 UTC, albertandrejev commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"RoundTable21 by WildSage Lab","identity":"3D1E44805E3D59D1","website":"https://wildsage.io/--detai
Please recreate your gentx, there is issue with website field, I guess you forgot one of the quotes at the end or space, so your website field contains `--description` field as well.

2022-11-03 21:11 UTC, albertandrejev commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"RoundTable21 by WildSage Lab","identity":"3D1E44805E3D59D1","website":"https://wildsage.io/--detai
Please recreate your gentx, there is issue with website field, I guess you forgot one of the quotes at the end or space, so your website field contains `--description` field as well.

2022-11-04 07:05 UTC, wildcommunist commented on quark/gentxs/gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"RoundTable21 by WildSage Lab","identity":"3D1E44805E3D59D1","website":"https://wildsage.io/--detai
Thanks @albertandrejev , changes implemented. While was at it, updated our peer too.
Thanks

2022-11-04 19:08 UTC, albertandrejev approved these changes

2022-11-06 18:56 UTC, merged