elf gentx & peer
neutron-org/testnets pull request #76
Opened 2022-11-02 12:33 UTC by elfelf2

2022-11-03 21:18 UTC, albertandrejev requested changes

2022-11-03 21:18 UTC, albertandrejev commented on quark/gentxs/elf-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"elf","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.100000
Please update `max_change_rate` and `max_rate` in accordance with the documentation.

2022-11-03 22:17 UTC, elfelf2 commented
elf
https://github.com/elfelf2
elfy#5077
neutronvaloper1rrl76e9809df84rnfqxdflw5wks2ayqasytdmc

2022-11-04 19:10 UTC, albertandrejev commented
I am afraid but it seems that your forgot to apply changes to your gentx. It is still the same.

2022-11-04 19:22 UTC, elfelf2 commented
Sorry for the confusion. I changed the gentx. Could you check it again?

2022-11-05 17:38 UTC, albertandrejev approved these changes

2022-11-06 22:22 UTC, merged