Add Lex_Prime gentx and peer
neutron-org/testnets pull request #79
Opened 2022-11-02 14:40 UTC by LexPrime

2022-11-04 13:50 UTC, albertandrejev requested changes

2022-11-04 13:50 UTC, albertandrejev commented on quark/gentxs/Lex_Prime-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Lex_Prime","identity":"0A7562DD5E1432EF","website":"https://t.me/lexxxprime","security_contact":"l
Please update `max_change_rate` in accordance with the documentation.

2022-11-04 20:19 UTC, LexPrime commented on quark/gentxs/Lex_Prime-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Lex_Prime","identity":"0A7562DD5E1432EF","website":"https://t.me/lexxxprime","security_contact":"l
Updated

2022-11-05 17:40 UTC, albertandrejev requested changes

2022-11-05 17:40 UTC, albertandrejev commented on quark/gentxs/Lex_Prime-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Lex_Prime","identity":"0A7562DD5E1432EF","website":"https://t.me/lexxxprime","security_contact":"l
Sorry, you need to recreate gentx with right parameter using command, it is not possible to update gentx content manually, it corrupts file.

2022-11-05 18:26 UTC, LexPrime commented on quark/gentxs/Lex_Prime-gentx.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Lex_Prime","identity":"0A7562DD5E1432EF","website":"https://t.me/lexxxprime","security_contact":"l
Ok, gentx recreated

2022-11-06 18:22 UTC, albertandrejev approved these changes

2022-11-06 22:28 UTC, merged